services:
  # Servicio de Scraping
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: atletismo-scraper
    user: "1000:1000"  # Usuario para evitar problemas de permisos
    volumes:
      - ./scraper/src:/app/src
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - atletismo-network
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1G

  # Servicio Web Astro - Generador de páginas estáticas
  web-builder:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: atletismo-web-builder
    volumes:
      - ./data:/tmp/data:ro
      - ./dist:/app/output
    env_file:
      - .env
    networks:
      - atletismo-network
    restart: "no"
    depends_on:
      - scraper

networks:
  atletismo-network:
    driver: bridge