services:
  # Servicio de Scraping
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: atletismo-scraper
    volumes:
      # Montar código fuente para desarrollo (opcional)
      - ./scraper/src:/app/src
      # Volumen para datos/resultados compartido
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - UPSLAT_USERNAME=gabriel.egallardor@gmail.com
      - UPSLAT_PASSWORD=5yS%4K&g**aVM47bp2DfmuY8sL!7x3oM
      - ATHLETES=Domingo Ruiz Tala,Gabriel Gallardo Rodriguez, Irma Andrea Sheihing Histchfeld, Joaequin Sebastian Erribarren Asenjo
    networks:
      - atletismo-network
    # No reiniciar el contenedor - ejecutar solo una vez
    restart: "no"
    profiles:
      - scraper
    # Configuración de recursos (opcional)
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  scraper-network:
    driver: bridge

volumes:
  scraper-data:
