services:
  # Servicio de Scraping
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: atletismo-scraper
    volumes:
      - ./scraper/src:/app/src
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - UPSLAT_USERNAME=gabriel.egallardor@gmail.com
      - UPSLAT_PASSWORD=5yS%4K&g**aVM47bp2DfmuY8sL!7x3oM
      - ATHLETES=Domingo Ruiz Tala,Gabriel Gallardo Rodriguez, Irma Andrea Sheihing Histchfeld, Joaequin Sebastian Erribarren Asenjo
    networks:
      - atletismo-network
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Servicio Web Astro - Constructor
  web-builder:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: atletismo-web-builder
    volumes:
      - ./data:/app/data:ro
      - ./dist:/app/output
    environment:
      - NODE_ENV=production
    networks:
      - atletismo-network
    restart: "no"

networks:
  atletismo-network:
    driver: bridge