name: Deploy to GitHub Pages

on:
  # Ejecutar manualmente
  workflow_dispatch:
  
  # Ejecutar automáticamente cada día a las 6:00 AM UTC
  schedule:
    - cron: '0 6 * * *'
  
  # Ejecutar en push a main
  push:
    branches:
      - main

# Permisos necesarios para GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Solo permitir un deployment a la vez
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  scrape-and-build:
    environment: scraper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create .env file
        run: |
          echo "UPSLAT_USERNAME=${{vars.UPSLAT_USERNAME}}" > .env
          echo "UPSLAT_PASSWORD=${{secrets.UPSLAT_PASSWORD}}" >> .env
          echo "ATHLETES=${{vars.ATHLETES}}" >> .env
          echo "NODE_ENV=production" >> .env
          
      - name: Create data directory with proper permissions
        run: |
          mkdir -p data
          mkdir -p pages
          # Dar permisos completos para evitar problemas con Docker
          chmod 777 data
          chmod 777 pages
          
      - name: Build and run scraper with Docker Compose
        run: |
          # Ejecutar solo el servicio scraper
          docker compose up --build scraper --abort-on-container-exit
          
          # Limpiar contenedores después del scraping
          docker compose down
          
      - name: Verify scraped data
        run: |
          echo "Checking scraped data..."
          ls -la data/ || echo "No data directory found"
          if [ -f "data/upslat-scrape-results.json" ]; then
            echo "Scraper data found!"
            wc -l data/upslat-scrape-results.json
          else
            echo "Warning: No scraper results found"
          fi
          
      - name: Build and run web builder with Docker Compose
        run: |
          # Ejecutar solo el servicio web-builder
          docker compose up --build web-builder --abort-on-container-exit
          
          # Limpiar contenedores después de la construcción
          docker compose down

      - name: Add .nojekyll file for GitHub Pages
        run: |
          touch pages/.nojekyll
          echo "Created .nojekyll file for GitHub Pages"
          
      - name: Clean up sensitive files
        run: |
          rm -f .env
          echo "Cleaned up temporary files"
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './pages'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: scrape-and-build
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
